log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    address: ':443'

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'tperons@gmail.com'
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: 'Host(`cars.tiagoperon.com.br`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    web-media-router:
      rule: '(Host(`cars.tiagoperon.com.br`)) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:8000

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
